export const data = {
    name: "Kunduru Santosh Reddy",
    role: "Software Engineer",
    availability: "open",
    location: "Hyderabad",
    email: "achyut1234duggal@gmail.com",
    image: "./neww.jpeg",
    resume: "https://drive.google.com/file/d/1AndKtbfOKIjdgWg1RdeLoL06RiyLjFYi/view?usp=sharing",
    experience: [
      {
        title: "Vertune (prepAIro)",
        image: "./stealth.jpeg",
        description: "Full Stack Application Intern",
        role: "Full Stack Application Intern",
        tags: ["2 mos"],
        href: "https://www.vertune.io/",
        duration: "2 mos",
      },
      {
        title: "MQS Technologies",
        image: "./mqs.jpeg",
        description: "Software and R&D Intern",
        role: "Software and R&D Intern",
        tags: ["3 mos"],
        href: "https://www.linkedin.com/company/https-mqstechnologies.in-/?originalSubdomain=in",
        duration: "3 mos",
      },
      {
        title: "MEEP",
        image: "./meep.jpeg",
        description: "Flutter",
        role: "Flutter",
        tags: ["0.5 yoe"],
        href: "",
        duration: "6 mos",
      },
    ],
    education: [
      {
        image: "./vit.jpeg",
        title: "Vellore Institute of Technology, Vellore",
        description: "Bachelor of Technology in Computer Science and Business Systems",
        tags: ["Vice Chairperson at roboVITics"],
        href: "https://vit.ac.in/",
      },
    ],
    projects:[
      {
        image: "./nextjslogo.jpg",
        title: "NextJS Portfolio",
        description: "A gallery of my career in programming, built simply with Next.js",
        tags: ["Next.js", "shadcn/ui", "Tailwind", "React"],
        href: "",
      },
      {
        image: "./python.jpeg",
        title: "AI-Driven Email Processing System",
        description: "Developed an AI-powered application to intelligently process and respond to email order requests and customer inquiries, comes with automatic inventory management system",
        tags: ["Python", "Open AI", "Google sheets", "GPT-4"],
        href: "https://colab.research.google.com/drive/1CCIVLkCmxn_xbB_-QDCIkvLUbUXpuNBC#scrollTo=UvOkHAkDghww",
      },
      {
        image: "./flutter.jpeg",
        title: "Gymnius",
        description: "A Flutter application, integrated with in-built Tensorflow model, which fetches the calories with a click of a photo",
        tags: ["Flutter", "Node.js", "Tensorflow", "Python"],
        href: "https://github.com/achyutduggal/gymnius_v1",
      },
      {
        image: "./raspberry.png",
        title: "PickerUpper",
        description: "Robot that picks up trash, automatically",
        tags: ["Raspberry pi", "Python", "Computer Vision", "Tensorflow"],
        href: "",
      },
    ]
  }